// <auto-generated />
using System;
using Backend.api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.api.Migrations
{
    [DbContext(typeof(ApplyAIDbContext))]
    [Migration("20260418170013_AddProfilePreferencesAndEnhancement")]
    partial class AddProfilePreferencesAndEnhancement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.api.Entities.AiDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiProcessingJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiProcessingJobId");

                    b.HasIndex("DraftId");

                    b.ToTable("AiDrafts");
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultFileId");

                    b.ToTable("AiJobs");
                });

            modelBuilder.Entity("Backend.api.Entities.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentRetracted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeOfConsent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CurrentCvId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferencesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProfileEnhancementJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ShortBio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.HasIndex("CurrentCvId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Backend.api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.api.Entities.S3File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AiProcessingJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiProcessingJobId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("S3File", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactKind")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Phase")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Phase");

                    b.ToTable("pipeline_artifacts", "llm_pipeline");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Activity")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("JobStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "OccurredAtUtc");

                    b.ToTable("pipeline_events", "llm_pipeline");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantAddressHint")
                        .HasColumnType("text");

                    b.Property<string>("CandidateFileSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CompanyNameOverride")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentActivity")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayRunName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IncludeAllConsentedFiles")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeCurrentCv")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeProfileRelevantDocuments")
                        .HasColumnType("boolean");

                    b.Property<string>("JobPostingContentType")
                        .HasColumnType("text");

                    b.Property<string>("JobPostingOriginalFileName")
                        .HasColumnType("text");

                    b.Property<string>("JobPostingReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobPostingSourceType")
                        .HasColumnType("integer");

                    b.Property<string>("PreferencesSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedArtifactsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RunStoragePrefix")
                        .HasColumnType("text");

                    b.Property<string>("SelectedFileIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorkflowMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("pipeline_jobs", "llm_pipeline");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelinePhaseState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ApprovedForDownstream")
                        .HasColumnType("boolean");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentActivity")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentId")
                        .HasColumnType("text");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("GateJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasUnverifiedEdits")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("RepairAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Phase")
                        .IsUnique();

                    b.ToTable("pipeline_phase_states", "llm_pipeline");
                });

            modelBuilder.Entity("Backend.api.Entities.Term", b =>
                {
                    b.HasBaseType("Backend.api.Entities.S3File");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = TRUE");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("Backend.api.Entities.AiDraft", b =>
                {
                    b.HasOne("Backend.api.Entities.AiProcessingJob", "AiProcessingJob")
                        .WithMany()
                        .HasForeignKey("AiProcessingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.api.Entities.S3File", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiProcessingJob");

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "ResultFile")
                        .WithMany()
                        .HasForeignKey("ResultFileId");

                    b.Navigation("ResultFile");
                });

            modelBuilder.Entity("Backend.api.Entities.Consent", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "CurrentCv")
                        .WithMany()
                        .HasForeignKey("CurrentCvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCv");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.RefreshToken", b =>
                {
                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.S3File", b =>
                {
                    b.HasOne("Backend.api.Entities.AiProcessingJob", null)
                        .WithMany("ProcessedFiles")
                        .HasForeignKey("AiProcessingJobId");

                    b.HasOne("Backend.api.Entities.Profile", null)
                        .WithMany("RelevantDocuments")
                        .HasForeignKey("ProfileId");

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineArtifact", b =>
                {
                    b.HasOne("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", "Job")
                        .WithMany("Artifacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineEvent", b =>
                {
                    b.HasOne("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", b =>
                {
                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelinePhaseState", b =>
                {
                    b.HasOne("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", "Job")
                        .WithMany("PhaseStates")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.api.Entities.Term", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", null)
                        .WithOne()
                        .HasForeignKey("Backend.api.Entities.Term", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.Navigation("ProcessedFiles");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.Navigation("RelevantDocuments");
                });

            modelBuilder.Entity("Backend.api.Services.ApplyAIService.ApplyAiPipelineJob", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Events");

                    b.Navigation("PhaseStates");
                });
#pragma warning restore 612, 618
        }
    }
}
