// <auto-generated />
using System;
using Backend.api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.api.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.api.Entities.AiDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiProcessingJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiProcessingJobId");

                    b.HasIndex("DraftId");

                    b.ToTable("AiDrafts");
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResultFileId");

                    b.ToTable("AiJobs");
                });

            modelBuilder.Entity("Backend.api.Entities.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentRetracted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeOfConsent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentCvId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCvId");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Backend.api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.api.Entities.S3File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AiProcessingJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiProcessingJobId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("S3File", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.api.Entities.Term", b =>
                {
                    b.HasBaseType("Backend.api.Entities.S3File");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = TRUE");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("Backend.api.Entities.AiDraft", b =>
                {
                    b.HasOne("Backend.api.Entities.AiProcessingJob", "AiProcessingJob")
                        .WithMany()
                        .HasForeignKey("AiProcessingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.api.Entities.S3File", "Draft")
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiProcessingJob");

                    b.Navigation("Draft");
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "ResultFile")
                        .WithMany()
                        .HasForeignKey("ResultFileId");

                    b.Navigation("ResultFile");
                });

            modelBuilder.Entity("Backend.api.Entities.Consent", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", "CurrentCv")
                        .WithMany()
                        .HasForeignKey("CurrentCvId");

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentCv");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.RefreshToken", b =>
                {
                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.S3File", b =>
                {
                    b.HasOne("Backend.api.Entities.AiProcessingJob", null)
                        .WithMany("ProcessedFiles")
                        .HasForeignKey("AiProcessingJobId");

                    b.HasOne("Backend.api.Entities.Profile", null)
                        .WithMany("RelevantDocuments")
                        .HasForeignKey("ProfileId");

                    b.HasOne("Backend.api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.api.Entities.Term", b =>
                {
                    b.HasOne("Backend.api.Entities.S3File", null)
                        .WithOne()
                        .HasForeignKey("Backend.api.Entities.Term", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.api.Entities.AiProcessingJob", b =>
                {
                    b.Navigation("ProcessedFiles");
                });

            modelBuilder.Entity("Backend.api.Entities.Profile", b =>
                {
                    b.Navigation("RelevantDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
